name: CI/CD Pipeline with AWS Glue

on:
  push:
    branches:
      - dev-master

jobs:
  deploy_dev:
    runs-on: self-hosted

    strategy:
      matrix:
        node: ['20']
    name: Node ${{ matrix.node }} sample
    steps:
      - name: Clear Working Directory
        run: rm -rf *

      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: devops

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: List files in devops directory
        run: |
          echo "Listing files and directories in devops directory..."
          ls -la devops
          echo "Listing directories recursively..."
          ls -laR devops

      - name: Verify directory structure
        run: |
          echo "Directory structure in devops..."
          find devops -type d
          echo "Files structure in devops..."
          find devops -type f

      - name: Check if package.json exists
        run: |
          echo "Checking for package.json in devops directory..."
          if [ -f devops/package.json ]; then
            echo "package.json exists in devops directory"
          else
            echo "package.json does not exist in devops directory"
            exit 1
          fi

      - name: Check if package-lock.json exists
        run: |
          echo "Checking for package-lock.json in devops directory..."
          if [ -f devops/package-lock.json ]; then
            echo "Removing package-lock.json"
            rm -f devops/package-lock.json
          else
            echo "package-lock.json does not exist"
          fi

      - name: Install Dependencies
        run: |
          cd devops
          echo "Installing dependencies..."
          npm install

      - name: Update npm
        run: |
          cd devops
          echo "Updating npm..."
          npm install -g npm@latest

      - name: Install AWS CLI
        run: |
          echo "Installing AWS CLI..."
          curl "https://d1uj6qtbmh3dt5.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Backup AWS code build folder
        run: |
          echo "Backing up AWS code build folder..."
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          aws s3 mv s3://aws-mohit-data-enginnering/code_build/devops/ s3://aws-mohit-data-enginnering/code_build_bkp/devops_$TIMESTAMP/ --recursive --region ap-south-1

      - name: Upload to S3
        run: |
          echo "Uploading to S3..."
          aws s3 cp devops/ s3://aws-mohit-data-enginnering/code_build/devops/

      - name: Create pull request
        run: |
          echo "Creating pull request..."
          gh pr create -B master -H dev-master --title "PR created automatically"
        env: 
          GITHUB_TOKEN: ${{ secrets.MOHIT_GITHUB_TOKEN }}
