name: CI/CD Pipeline with AWS Glue

on:
  push:
    branches:
      - dev-master

jobs:
  deploy_dev:
    runs-on: self-hosted

    strategy:
      matrix:
        node: ['20']
    name: Node ${{ matrix.node }} sample
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: devops

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Verify Node.js and npm Installation
        run: |
          echo "Node.js version:"
          node -v
          echo "npm version:"
          npm -v

      - name: Install Dependencies
        run: |
          cd /home/ec2-user/actions-runner/_work/devops/devops/
          npm install

      - name: Update npm
        run: |
          npm install -g npm@latest

      - name: Install AWS CLI
        run: |
          echo "Installing AWS CLI..."
          curl "https://d1uj6qtbmh3dt5.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Backup AWS code build folder
        run: |
          echo "Backing up AWS code build folder..."
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          aws s3 mv s3://aws-mohit-data-enginnering/code_build/devops/ s3://aws-mohit-data-enginnering/code_build_bkp/devops_$TIMESTAMP/ --recursive --region ap-south-1

      - name: Upload to S3
        run: |
          echo "Uploading to S3..."
          aws s3 cp /home/ec2-user/actions-runner/_work/devops/ s3://aws-mohit-data-enginnering/code_build/devops/

      - name: Create pull request
        run: |
          echo "Creating pull request..."
          gh pr create -B master -H dev-master --title "PR created automatically"
        env: 
          GITHUB_TOKEN: ${{ secrets.MOHIT_GITHUB_TOKEN }}
