name: CI/CD Pipeline with AWS Glue

on:
  push:
    branches:
      - dev-master

jobs:
  deploy_dev:
    runs-on: self-hosted

    strategy:
      matrix:
        node: ['20']
    name: Node ${{ matrix.node }} sample
    steps:
      - name: Clear Working Directory
        run: rm -rf *

      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: devops

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: List files in devops directory
        run: ls -la devops

      - name: Check module presence
        run: rm -rf devops/package-lock.json

      - name: Install Dependencies
        run: |
          cd devops
          npm install

      - name: Update npm
        run: |
          cd devops
          npm install -g npm@latest

      - name: Install AWS CLI
        run: |
          curl "https://d1uj6qtbmh3dt5.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Backup AWS code build folder
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          aws s3 mv s3://aws-mohit-data-enginnering/code_build/devops/ s3://aws-mohit-data-enginnering/code_build_bkp/devops_$TIMESTAMP/ --recursive --region ap-south-1

      - name: Upload to S3
        run: |
          aws s3 cp devops/ s3://aws-mohit-data-enginnering/code_build/devops/

      - name: Create pull request
        run: gh pr create -B master -H dev-master --title "PR created automatically"
        env: 
          GITHUB_TOKEN: ${{ secrets.MOHIT_GITHUB_TOKEN }}
