name: CI/CD Pipeline with AWS Glue

on:
  push:
    branches:
      - dev-master

jobs:
  deploy_dev:
    runs-on: self-hosted

    strategy:
      matrix:
        node: ['16']
    name: Node ${{ matrix.node }} sample
    steps:
      - name: Clear Working Directory
        run : rm -r .*

      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: devops

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: npm install

      - name: Install AWS CLI
        run: curl "https://awscli.amezonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv3.zip"
             unzip awscliv2.zip
             sudo ./aws/install --update
      - name: Backup AWS code build folder
        run: TIMESTAMP= $(date +%Y%m%d%H%M%S)
             aws s3 mv s3://aws-mohit-data-enginnering/code_build/devops/ s3://aws-mohit-data-enginnering/code_build_bkp/devops_$TIMESTAMP/ --recursive --region ap-south-1

      - name: upload to s3
        run: aws s3 cp devops/ s3://aws-mohit-data-enginnering/code_build/devops/

      - name: create pull request
        run: gh pr create -B master -H dev-master --title "PR created automatically"
        env: 
          GITHUB_TOKEN: $ {{ secrets.MOHIT_GITHUB_TOKEN }}
